events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:5000/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /patient/ {
            proxy_pass http://patient-service:5000/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /admin/ {
            proxy_pass http://admin-service:5000/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /dashboard/ {
            proxy_pass http://dashboard:5000/;
            proxy_set_header Host $host;
        }
    }
}